-- Add a cross-source set of foundational strength and stability exercises that
-- were missing from the shared catalog. The demo links point to the official
-- publisher uploads; the artwork is original FWB-branded media.
with new_exercises as (
  select *
  from jsonb_to_recordset($exercises$
  [
    {
      "name":"Barbell Row",
      "aliases":["Barbell Bent-Over Row","Bent-Over Barbell Row","Bent Over Row"],
      "primary_muscle":"back",
      "secondary_muscles":["lats","biceps"],
      "equipment":"barbell",
      "difficulty":"intermediate",
      "movement_pattern":"horizontal_pull",
      "default_sets":3,
      "default_reps":"8-12",
      "default_rest_seconds":75,
      "substitution_group":"horizontal_pull",
      "sort_order":1080,
      "slug":"barbell-row",
      "demo_url":"https://www.youtube.com/watch?v=TZLCvXbej_Q",
      "instructions":"Stand with your feet about hip-width apart and hold the bar just outside your legs. Hinge at the hips with a braced, neutral torso and let the bar hang beneath your shoulders. Pull the bar toward your lower ribs while keeping your elbows close, pause without shrugging, then lower it under control without changing your torso angle."
    },
    {
      "name":"Reverse Lunge",
      "aliases":["Backward Lunge","Step-Back Lunge"],
      "primary_muscle":"quads",
      "secondary_muscles":["glutes","hamstrings"],
      "equipment":"bodyweight",
      "difficulty":"beginner",
      "movement_pattern":"single_leg_squat",
      "default_sets":3,
      "default_reps":"8-12 each",
      "default_rest_seconds":60,
      "substitution_group":"single_leg_squat",
      "sort_order":1081,
      "slug":"reverse-lunge",
      "demo_url":"https://www.youtube.com/watch?v=TQfhY5oJ_Sc",
      "instructions":"Stand tall with your feet under your hips. Step one foot back and lower both knees while keeping the front foot planted and the front knee tracking over the middle toes. Lightly approach the floor with the rear knee, then drive through the front foot to return to standing. Keep your torso controlled and alternate sides."
    },
    {
      "name":"Cable Pull-Through",
      "aliases":["Cable Hip Hinge","Rope Pull-Through"],
      "primary_muscle":"glutes",
      "secondary_muscles":["hamstrings"],
      "equipment":"cable",
      "difficulty":"intermediate",
      "movement_pattern":"hinge",
      "default_sets":3,
      "default_reps":"10-15",
      "default_rest_seconds":60,
      "substitution_group":"hip_hinge",
      "sort_order":1082,
      "slug":"cable-pull-through",
      "demo_url":"https://www.youtube.com/watch?v=pv8e6OSyETE",
      "instructions":"Face away from a low cable and hold the rope between your legs. Walk forward until the cable is taut, soften your knees, and push your hips back while keeping your spine neutral. Drive your hips forward to stand tall and squeeze your glutes without leaning backward, then hinge again under control."
    },
    {
      "name":"Nordic Hamstring Curl",
      "aliases":["Natural Glute-Ham Raise","Nordic Curl","Nordic Hamstring Exercise"],
      "primary_muscle":"hamstrings",
      "secondary_muscles":["glutes"],
      "equipment":"bodyweight",
      "difficulty":"advanced",
      "movement_pattern":"knee_flexion",
      "default_sets":3,
      "default_reps":"4-8",
      "default_rest_seconds":90,
      "substitution_group":"hamstring_curl",
      "sort_order":1083,
      "slug":"nordic-hamstring-curl",
      "demo_url":"https://www.youtube.com/watch?v=_e9vFU9-tkc",
      "instructions":"Kneel on padding with your ankles securely anchored and keep a straight line from your knees through your head. Brace your trunk and slowly lower your body forward by extending at the knees while resisting with your hamstrings. Use your hands to catch yourself when needed, then push lightly from the floor and pull with the hamstrings to return."
    },
    {
      "name":"Copenhagen Plank",
      "aliases":["Adductor Side Plank","Copenhagen Side Plank"],
      "primary_muscle":"adductors",
      "secondary_muscles":["core"],
      "equipment":"bench",
      "difficulty":"intermediate",
      "movement_pattern":"core_stability",
      "default_sets":3,
      "default_reps":"15-30 sec each",
      "default_rest_seconds":45,
      "substitution_group":"adductor_strength",
      "sort_order":1084,
      "slug":"copenhagen-plank",
      "demo_url":"https://www.youtube.com/watch?v=kD1t1hWzIDE",
      "instructions":"Lie on your side with the top foot or lower leg supported on a bench and your elbow beneath your shoulder. Press the supported leg into the bench and lift your hips until your body forms a straight line. Keep your ribs and pelvis stacked while the lower leg stays off the floor, hold with steady breathing, then lower and repeat on the other side."
    },
    {
      "name":"Sumo Deadlift",
      "aliases":["Barbell Sumo Deadlift","Wide-Stance Deadlift"],
      "primary_muscle":"glutes",
      "secondary_muscles":["hamstrings","quads","adductors"],
      "equipment":"barbell",
      "difficulty":"intermediate",
      "movement_pattern":"hinge",
      "default_sets":3,
      "default_reps":"6-10",
      "default_rest_seconds":90,
      "substitution_group":"deadlift",
      "sort_order":1085,
      "slug":"sumo-deadlift",
      "demo_url":"https://www.youtube.com/watch?v=GyeXtU8vj-Y",
      "instructions":"Take a wide stance with your toes turned out comfortably and the bar over midfoot. Grip the bar inside your knees, brace your trunk, and push your knees in line with your toes. Drive the floor away and stand by extending your knees and hips together. Finish tall without leaning back, then return the bar under control."
    },
    {
      "name":"Suitcase Carry",
      "aliases":["Single-Arm Farmer Carry","Single-Arm Farmers Walk","Suitcase Walk"],
      "primary_muscle":"core",
      "secondary_muscles":["forearms","shoulders"],
      "equipment":"other",
      "difficulty":"beginner",
      "movement_pattern":"carry",
      "default_sets":3,
      "default_reps":"20-40 m each",
      "default_rest_seconds":60,
      "substitution_group":"loaded_carry",
      "sort_order":1086,
      "slug":"suitcase-carry",
      "demo_url":"https://www.youtube.com/watch?v=LJaq4BS7KpE",
      "instructions":"Stand tall holding one heavy dumbbell or kettlebell at your side. Keep your shoulders level, ribs stacked over your pelvis, and the weight from pulling you sideways. Walk with controlled, natural steps while maintaining an upright posture. Set the weight down safely, turn around, and repeat on the opposite side."
    },
    {
      "name":"Band External Rotation",
      "aliases":["Resistance Band External Rotation","Rotator Cuff External Rotation","Standing Band External Rotation"],
      "primary_muscle":"shoulders",
      "secondary_muscles":[],
      "equipment":"other",
      "difficulty":"beginner",
      "movement_pattern":"external_rotation",
      "default_sets":2,
      "default_reps":"12-15 each",
      "default_rest_seconds":45,
      "substitution_group":"rotator_cuff",
      "sort_order":1087,
      "slug":"band-external-rotation",
      "demo_url":"https://www.youtube.com/watch?v=ZJgOL828OvY",
      "instructions":"Anchor a light resistance band near elbow height and stand with the working side away from the anchor. Bend that elbow to 90 degrees and keep it gently against your side. Rotate your forearm outward without moving your elbow, shoulder, or torso, pause in a comfortable range, then return slowly while maintaining band tension."
    }
  ]$exercises$::jsonb) as exercise(
    name text,
    aliases text[],
    primary_muscle text,
    secondary_muscles text[],
    equipment text,
    difficulty text,
    movement_pattern text,
    default_sets integer,
    default_reps text,
    default_rest_seconds integer,
    substitution_group text,
    sort_order integer,
    slug text,
    demo_url text,
    instructions text
  )
)
insert into public.exercise_library (
  name,
  aliases,
  primary_muscle,
  secondary_muscles,
  equipment,
  difficulty,
  movement_pattern,
  default_sets,
  default_reps,
  default_rest_seconds,
  substitution_group,
  image_url,
  demo_url,
  instructions,
  is_approved,
  is_active,
  sort_order
)
select
  name,
  aliases,
  primary_muscle,
  secondary_muscles,
  equipment,
  difficulty,
  movement_pattern,
  default_sets,
  default_reps,
  default_rest_seconds,
  substitution_group,
  'https://qukdfjeupjhpthfbaonv.supabase.co/storage/v1/object/public/exercise-images/approved/2026-09-30/webp-768/' || slug || '.webp',
  demo_url,
  instructions,
  true,
  true,
  sort_order
from new_exercises
on conflict (lower(name)) do update set
  aliases = (
    select array_agg(distinct alias order by alias)
    from unnest(coalesce(public.exercise_library.aliases, '{}'::text[]) || excluded.aliases) as alias
  ),
  primary_muscle = excluded.primary_muscle,
  secondary_muscles = excluded.secondary_muscles,
  equipment = excluded.equipment,
  difficulty = excluded.difficulty,
  movement_pattern = excluded.movement_pattern,
  default_sets = excluded.default_sets,
  default_reps = excluded.default_reps,
  default_rest_seconds = excluded.default_rest_seconds,
  substitution_group = excluded.substitution_group,
  image_url = excluded.image_url,
  demo_url = excluded.demo_url,
  instructions = excluded.instructions,
  is_approved = true,
  is_active = true,
  sort_order = excluded.sort_order,
  updated_at = now();
