-- Queue native iOS alerts for the same private in-app notifications used by web.
-- APNs credentials stay in Edge Function secrets; database rows never contain them.

create table if not exists public.fwb_native_push_queue (
  id bigint generated by default as identity primary key,
  notification_id uuid not null references public.client_notifications(id) on delete cascade,
  device_id uuid not null references public.client_notification_devices(id) on delete cascade,
  available_at timestamptz not null default now(),
  locked_at timestamptz,
  attempts smallint not null default 0 check (attempts between 0 and 10),
  delivered_at timestamptz,
  last_error text check (last_error is null or char_length(last_error) <= 500),
  created_at timestamptz not null default now(),
  unique (notification_id, device_id)
);

create index if not exists fwb_native_push_queue_pending_idx
  on public.fwb_native_push_queue (available_at, id)
  where delivered_at is null and attempts < 10;

alter table public.fwb_native_push_queue enable row level security;
revoke all on table public.fwb_native_push_queue from public, anon, authenticated;
grant select, insert, update, delete on table public.fwb_native_push_queue to service_role;

create or replace function private.fwb_enqueue_native_push()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.fwb_native_push_queue (notification_id, device_id)
  select new.id, device.id
    from public.client_notification_devices as device
   where device.user_id = new.user_id
     and device.platform = 'ios'
     and device.is_active is true
     and device.bundle_identifier = 'com.benjaminbenz.fwbcoach'
  on conflict (notification_id, device_id) do nothing;

  return new;
end;
$$;

revoke all on function private.fwb_enqueue_native_push() from public, anon, authenticated;

drop trigger if exists fwb_enqueue_native_push on public.client_notifications;
create trigger fwb_enqueue_native_push
after insert on public.client_notifications
for each row execute function private.fwb_enqueue_native_push();

create or replace function public.fwb_claim_native_push_jobs(p_limit integer default 50)
returns table (
  queue_id bigint,
  notification_id uuid,
  device_id uuid,
  user_id uuid,
  device_token text,
  environment text,
  bundle_identifier text,
  notification_kind text,
  notification_title text,
  notification_created_at timestamptz,
  notification_read_at timestamptz,
  attempts smallint
)
language sql
security definer
set search_path = ''
as $$
  with claimed as (
    select queue.id
      from public.fwb_native_push_queue as queue
     where queue.delivered_at is null
       and queue.attempts < 10
       and queue.available_at <= now()
       and (queue.locked_at is null or queue.locked_at < now() - interval '5 minutes')
     order by queue.available_at, queue.id
     for update skip locked
     limit least(greatest(coalesce(p_limit, 50), 1), 100)
  ), updated as (
    update public.fwb_native_push_queue as queue
       set locked_at = now(),
           attempts = queue.attempts + 1
      from claimed
     where queue.id = claimed.id
     returning queue.*
  )
  select updated.id,
         notification.id,
         device.id,
         notification.user_id,
         device.device_token,
         device.environment,
         device.bundle_identifier,
         coalesce(notification.web_category, notification.kind),
         notification.title,
         notification.created_at,
         notification.read_at,
         updated.attempts
    from updated
    join public.client_notifications as notification
      on notification.id = updated.notification_id
    join public.client_notification_devices as device
      on device.id = updated.device_id
   where device.user_id = notification.user_id
     and device.is_active is true;
$$;

revoke all on function public.fwb_claim_native_push_jobs(integer) from public, anon, authenticated;
grant execute on function public.fwb_claim_native_push_jobs(integer) to service_role;

do $$
begin
  if exists (select 1 from cron.job where jobname = 'fwb-native-push-delivery') then
    perform cron.unschedule('fwb-native-push-delivery');
  end if;
end;
$$;

select cron.schedule(
  'fwb-native-push-delivery',
  '* * * * *',
  $cron$
    select net.http_post(
      url := 'https://qukdfjeupjhpthfbaonv.supabase.co/functions/v1/fwb-native-push',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', 'Bearer ' || (
          select decrypted_secret
            from vault.decrypted_secrets
           where name = 'fwb_push_worker_token'
           limit 1
        )
      ),
      body := '{}'::jsonb,
      timeout_milliseconds := 15000
    );
  $cron$
);
