-- Point exact, active, approved exercise-library matches at the reviewed branded
-- start/end cards. The original PNG masters and 480px WebPs live beside these
-- canonical 768px WebPs in the same versioned storage release.
with media as (
  select exercise_name, slug
  from jsonb_to_recordset($media$
[
  {"exercise_name":"45° Degree Back Extension","slug":"45-degree-back-extension"},
  {"exercise_name":"45° Degree Glute Drive Machine","slug":"45-degree-glute-drive-machine"},
  {"exercise_name":"45° Degree Hip Extension","slug":"45-degree-hip-extension"},
  {"exercise_name":"45° Degree Lean Lateral Raise","slug":"45-degree-lean-lateral-raise"},
  {"exercise_name":"Ab Coaster","slug":"ab-coaster"},
  {"exercise_name":"Ab Wheel Rollout","slug":"ab-wheel-rollout"},
  {"exercise_name":"Assisted Dip","slug":"assisted-dip"},
  {"exercise_name":"Assisted Pull Up","slug":"assisted-pull-up"},
  {"exercise_name":"Barbell Bench Press","slug":"barbell-bench-press"},
  {"exercise_name":"Barbell Curl","slug":"barbell-curl"},
  {"exercise_name":"Bench Dip","slug":"bench-dip"},
  {"exercise_name":"Bicycle Kicks","slug":"bicycle-kicks"},
  {"exercise_name":"BOSU Push Up","slug":"bosu-push-up"},
  {"exercise_name":"Bulgarian Split Squat","slug":"bulgarian-split-squat"},
  {"exercise_name":"Cable Chest Fly","slug":"cable-chest-fly"},
  {"exercise_name":"Cable Crunch","slug":"cable-crunch"},
  {"exercise_name":"Cable Curl","slug":"cable-curl"},
  {"exercise_name":"Cable Glute Kickback","slug":"cable-glute-kickback"},
  {"exercise_name":"Cable Rotation","slug":"cable-rotation"},
  {"exercise_name":"Cable Woodchop","slug":"cable-woodchop"},
  {"exercise_name":"Cat Cow","slug":"cat-cow"},
  {"exercise_name":"Chest Supported Dumbbell Row","slug":"chest-supported-dumbbell-row"},
  {"exercise_name":"Close Grip Lat Pulldown","slug":"close-grip-lat-pulldown"},
  {"exercise_name":"Cross Body Shoulder Stretch","slug":"cross-body-shoulder-stretch"},
  {"exercise_name":"Dead Bug","slug":"dead-bug"},
  {"exercise_name":"Decline Chest Press","slug":"decline-chest-press"},
  {"exercise_name":"Dumbbell Bench Press","slug":"dumbbell-bench-press"},
  {"exercise_name":"Dumbbell Chest Fly","slug":"dumbbell-chest-fly"},
  {"exercise_name":"Dumbbell Curl","slug":"dumbbell-curl"},
  {"exercise_name":"Dumbbell Grave Digger","slug":"dumbbell-grave-digger"},
  {"exercise_name":"Dumbbell Lateral Raise","slug":"dumbbell-lateral-raise"},
  {"exercise_name":"Dumbbell Reverse Fly","slug":"dumbbell-reverse-fly"},
  {"exercise_name":"Dumbbell Romanian Deadlift","slug":"dumbbell-romanian-deadlift"},
  {"exercise_name":"Dumbbell Step Up","slug":"dumbbell-step-up"},
  {"exercise_name":"Dumbbell Triceps Kickback","slug":"dumbbell-triceps-kickback"},
  {"exercise_name":"Face Pull","slug":"face-pull"},
  {"exercise_name":"Plank","slug":"forearm-plank"},
  {"exercise_name":"Frog Stretch","slug":"frog-stretch"},
  {"exercise_name":"Glute Machine Bulgarian Split Squat","slug":"glute-machine-bulgarian-split-squat"},
  {"exercise_name":"Goblet Squat","slug":"goblet-squat"},
  {"exercise_name":"Hack Squat","slug":"hack-squat"},
  {"exercise_name":"Half Kneeling Hip Flexor Stretch","slug":"half-kneeling-hip-flexor-stretch"},
  {"exercise_name":"Hammer Curl","slug":"hammer-curl"},
  {"exercise_name":"Hanging Knee Raise","slug":"hanging-knee-raise"},
  {"exercise_name":"Heel Elevated Squat","slug":"heel-elevated-squat"},
  {"exercise_name":"Hip Abduction Machine","slug":"hip-abduction-machine"},
  {"exercise_name":"Hip Adduction Machine","slug":"hip-adduction-machine"},
  {"exercise_name":"Hip Thrust","slug":"hip-thrust"},
  {"exercise_name":"Hip Thrust Machine","slug":"hip-thrust-machine"},
  {"exercise_name":"Incline Barbell Bench Press","slug":"incline-barbell-bench-press"},
  {"exercise_name":"Incline Cable Fly","slug":"incline-cable-fly"},
  {"exercise_name":"Incline Dumbbell Curl","slug":"incline-dumbbell-curl"},
  {"exercise_name":"Incline Dumbbell Fly","slug":"incline-dumbbell-fly"},
  {"exercise_name":"Incline Dumbbell Press","slug":"incline-dumbbell-press"},
  {"exercise_name":"Incline Machine Chest Press","slug":"incline-machine-chest-press"},
  {"exercise_name":"Jesus Christ Curl","slug":"jesus-christ-curl"},
  {"exercise_name":"Jumping Jacks","slug":"jumping-jacks"},
  {"exercise_name":"Lat Pulldown","slug":"lat-pulldown"},
  {"exercise_name":"Leg Extension","slug":"leg-extension"},
  {"exercise_name":"Leg Press","slug":"leg-press"},
  {"exercise_name":"Lying Leg Raise","slug":"lying-leg-lifts"},
  {"exercise_name":"Machine Chest Press","slug":"machine-chest-press"},
  {"exercise_name":"Glute Kickback Machine","slug":"machine-glute-kickback"},
  {"exercise_name":"Machine Shoulder Press","slug":"machine-shoulder-press"},
  {"exercise_name":"Mountain Climber","slug":"mountain-climber"},
  {"exercise_name":"One Arm Dumbbell Row","slug":"one-arm-dumbbell-row"},
  {"exercise_name":"One Dumbbell Bulgarian Split Squat","slug":"one-dumbbell-bulgarian-split-squat"},
  {"exercise_name":"Overhead Cable Triceps Extension","slug":"overhead-cable-triceps-extension"},
  {"exercise_name":"Overhead Triceps Stretch","slug":"overhead-triceps-stretch"},
  {"exercise_name":"Pallof Press","slug":"pallof-press"},
  {"exercise_name":"Pec Deck Chest Fly","slug":"pec-deck-fly"},
  {"exercise_name":"Pistol Squat","slug":"pistol-squat"},
  {"exercise_name":"Preacher Curl","slug":"preacher-curl"},
  {"exercise_name":"Pull Up","slug":"pull-up"},
  {"exercise_name":"Push Up","slug":"push-up"},
  {"exercise_name":"Reverse Fly","slug":"reverse-fly"},
  {"exercise_name":"Romanian Deadlift","slug":"romanian-deadlift"},
  {"exercise_name":"Rope Triceps Pressdown","slug":"rope-triceps-pressdown"},
  {"exercise_name":"Russian Twist","slug":"russian-twist"},
  {"exercise_name":"Seated Butterfly Stretch","slug":"seated-butterfly-stretch"},
  {"exercise_name":"Seated Cable Fly","slug":"seated-cable-fly"},
  {"exercise_name":"Seated Cable Row","slug":"seated-cable-row"},
  {"exercise_name":"Seated Calf Raise","slug":"seated-calf-raise"},
  {"exercise_name":"Seated Dip Machine","slug":"seated-dip-machine"},
  {"exercise_name":"Seated Dumbbell Shoulder Press","slug":"seated-dumbbell-shoulder-press"},
  {"exercise_name":"Seated Leg Curl","slug":"seated-leg-curl"},
  {"exercise_name":"Shoulder Circles","slug":"shoulder-circles"},
  {"exercise_name":"Side Lying Open Book","slug":"side-lying-open-book"},
  {"exercise_name":"Side Lying Quad Stretch","slug":"side-lying-quad-stretch"},
  {"exercise_name":"Side Plank","slug":"side-plank"},
  {"exercise_name":"Single Leg Dumbbell RDL","slug":"single-leg-dumbbell-rdl"},
  {"exercise_name":"Single Leg Hip Thrust","slug":"single-leg-hip-thrust"},
  {"exercise_name":"Sit Up","slug":"sit-up"},
  {"exercise_name":"Smith Machine Front Foot Elevated Split Squat","slug":"smith-machine-front-foot-elevated-split-squat"},
  {"exercise_name":"Smith Machine Split Squat","slug":"smith-machine-split-squat"},
  {"exercise_name":"Smith Machine Squat","slug":"smith-machine-squat"},
  {"exercise_name":"Stability Ball Woodchop","slug":"stability-ball-woodchop"},
  {"exercise_name":"Standing Calf Raise","slug":"standing-calf-raise"},
  {"exercise_name":"Standing Dumbbell Shoulder Press","slug":"standing-dumbbell-shoulder-press"},
  {"exercise_name":"Standing Incline Cable Curl","slug":"standing-incline-cable-curl"},
  {"exercise_name":"Standing Leg Curl","slug":"standing-leg-curl"},
  {"exercise_name":"Supine Chest Stretch","slug":"supine-chest-stretch"},
  {"exercise_name":"Supine Figure Four Stretch","slug":"supine-figure-four-stretch"},
  {"exercise_name":"Supine Hamstring Stretch","slug":"supine-hamstring-stretch"},
  {"exercise_name":"Two Dumbbell Bulgarian Split Squat","slug":"two-dumbbell-bulgarian-split-squat"},
  {"exercise_name":"Walking Lunge","slug":"walking-lunge"}
]$media$::jsonb) as record(exercise_name text, slug text)
)
update public.exercise_library as exercise
set image_url = 'https://qukdfjeupjhpthfbaonv.supabase.co/storage/v1/object/public/exercise-images/approved/2026-09-29/webp-768/' || media.slug || '.webp'
from media
where trim(both '-' from regexp_replace(lower(exercise.name), '[^a-z0-9]+', '-', 'g'))
    = trim(both '-' from regexp_replace(lower(media.exercise_name), '[^a-z0-9]+', '-', 'g'))
  and exercise.is_approved
  and exercise.is_active
returning exercise.id, exercise.name, exercise.image_url;
