-- Reusable weekly workout plans generated by clients in the web app.
create table public.client_saved_workout_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  plan jsonb not null check (jsonb_typeof(plan) = 'object'),
  created_at timestamptz not null default now()
);

create index client_saved_workout_plans_owner_created_idx
  on public.client_saved_workout_plans (user_id, created_at desc);

alter table public.client_saved_workout_plans enable row level security;
revoke all on public.client_saved_workout_plans from anon, authenticated;
grant select, insert, delete on public.client_saved_workout_plans to authenticated;

create policy "Clients read their saved workout plans"
  on public.client_saved_workout_plans for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Clients create their saved workout plans"
  on public.client_saved_workout_plans for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Clients delete their saved workout plans"
  on public.client_saved_workout_plans for delete to authenticated
  using ((select auth.uid()) = user_id);
