-- Link the reviewed exercise artwork without replacing any existing image.
with approved_images (object_name) as (
values
  ('45-degree-back-extension.png'),
  ('barbell-bench-press.png'),
  ('barbell-curl.png'),
  ('bench-dip.png'),
  ('bulgarian-split-squat.png'),
  ('cable-chest-fly.png'),
  ('cable-crunch.png'),
  ('cable-curl.png'),
  ('cable-glute-kickback.png'),
  ('cat-cow.png'),
  ('chest-supported-dumbbell-row.png'),
  ('close-grip-lat-pulldown.png'),
  ('cross-body-shoulder-stretch.png'),
  ('dead-bug.png'),
  ('dumbbell-bench-press.png'),
  ('dumbbell-chest-fly.png'),
  ('dumbbell-curl.png'),
  ('dumbbell-lateral-raise.png'),
  ('dumbbell-reverse-fly.png'),
  ('dumbbell-romanian-deadlift.png'),
  ('face-pull.png'),
  ('goblet-squat.png'),
  ('hack-squat.png'),
  ('half-kneeling-hip-flexor-stretch.png'),
  ('hammer-curl.png'),
  ('hanging-knee-raise.png'),
  ('hip-adduction-machine.png'),
  ('hip-thrust.png'),
  ('hip-thrust-machine.png'),
  ('incline-dumbbell-curl.png'),
  ('incline-dumbbell-press.png'),
  ('incline-machine-chest-press.png'),
  ('lat-pulldown.png'),
  ('leg-extension.png'),
  ('leg-press.png'),
  ('lying-leg-raise.png'),
  ('machine-chest-press.png'),
  ('machine-shoulder-press.png'),
  ('one-arm-dumbbell-row.png'),
  ('overhead-cable-triceps-extension.png'),
  ('overhead-triceps-stretch.png'),
  ('pallof-press.png'),
  ('plank.png'),
  ('preacher-curl.png'),
  ('pull-up.png'),
  ('push-up.png'),
  ('reverse-fly.png'),
  ('rope-triceps-pressdown.png'),
  ('seated-butterfly-stretch.png'),
  ('seated-cable-row.png'),
  ('seated-calf-raise.png'),
  ('seated-dip-machine.png'),
  ('seated-dumbbell-shoulder-press.png'),
  ('seated-leg-curl.png'),
  ('shoulder-circles.png'),
  ('side-lying-open-book.png'),
  ('side-lying-quad-stretch.png'),
  ('side-plank.png'),
  ('standing-calf-raise.png'),
  ('standing-dumbbell-shoulder-press.png'),
  ('standing-leg-curl.png'),
  ('supine-chest-stretch.png'),
  ('supine-figure-four-stretch.png'),
  ('supine-hamstring-stretch.png')
)
update public.exercise_library as exercise
set image_url = 'https://qukdfjeupjhpthfbaonv.supabase.co/storage/v1/object/public/exercise-images/approved/' || image.object_name
from approved_images as image
where trim(both '-' from regexp_replace(lower(exercise.name), '[^a-z0-9]+', '-', 'g')) || '.png' = image.object_name
  and exercise.is_approved
  and exercise.is_active
  and exercise.image_url is null;
